Add method to get vacant key without mutable access
tokio-rs/slab pull request #114
Opened 2022-03-17 20:45 UTC by binier

Same as `slab.vacant_entry().key()` without requiring mutable access.

2022-03-17 22:06 UTC, taiki-e approved these changes
Thanks!

2022-03-17 23:50 UTC, hawkw requested changes
Some small suggestions for the docs.

2022-03-17 23:50 UTC, hawkw commented on src/lib.rs
> +    /// Same as `slab.vacant_entry().key()` but doesn't require mutable access.
i might reword this a bit:
```suggestion
    /// Returns the key of the next vacant entry.
    ///
    /// This function returns the key of the vacant entry which  will be used
    /// for the next insertion. This is equivalent to
    /// `slab.vacant_entry().key()`, but it doesn't require mutable access.
```

2022-03-18 04:56 UTC, binier commented on src/lib.rs
> +    /// Same as `slab.vacant_entry().key()` but doesn't require mutable access.
Thanks @hawkw  :)

2022-03-18 16:57 UTC, hawkw approved these changes
looks good to me --- thanks for the docs changes!

2022-03-23 10:47 UTC, merged